services:
  db:
    container_name: postgres-clinique
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rajabarca
      POSTGRES_DB: clinique-DB
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  pgadmin:
    container_name: pgadmin4_Clinique
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: yassine@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8082:80"

volumes:
  db_data: